# Generated by Django 2.0.4 on 2018-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_posts_pictures/'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
