# Generated by Django 2.0.4 on 2018-05-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
