# Generated by Django 2.0.4 on 2018-04-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('description', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
