# Generated by Django 2.0.4 on 2018-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0007_auto_20180518_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
